# Generated by Django 3.2 on 2021-02-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_webpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='pagerank',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
