# Generated by Django 3.2 on 2021-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_webpage_pagerank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='pagerank',
            field=models.FloatField(default=0),
        ),
    ]
