# Generated by Django 3.2 on 2021-02-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_webpage_pagerank'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebpageTokenCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('count', models.IntegerField()),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.webpage')),
            ],
        ),
    ]
